version: '3.8'

services:
  address_module:
    env_file:
      - "../.env"
    build:
      context: .
    container_name: address_module
    restart: always
    ports:
      - "9080:8080"
    environment:
      MODULE_GROUP_ID: ADDRESS_GROUP_ID
      SERVICE_PORT: 9080
#    deploy:
#      mode: replicated
#      replicas: 2

